package boya.microservice.demo.api.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;

/**
 * Created by boyagaga on 3/18/16.
 */

@Entity
@Table(name = "Demo_Product")
public class Product implements Serializable {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    // The user's email
    @NotNull
    private String name;

    // The user's name
    @NotNull
    private String desc;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }
} // class Product


